# Generated by Django 2.0 on 2017-12-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171226_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book2Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Book')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='book2author',
            unique_together={('author', 'book')},
        ),
    ]
